name: Validate Build

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
